path:
  laughter:
    path: /home/xindetai/Downloads/laughter_open
  processed_path: ./data/laughter
view:
  val: 128
  test_speaker: 1
  test_wav_per_speaker: 128
  kmeans_filelist: ./filelists/laughter_kmeans.txt
  train_filelist: ./filelists/laughter_train.txt
  val_filelist: ./filelists/laughter_val.txt
  test_filelist: ./filelists/laughter_test.txt
audio:
  sr: 16000
  normalization: False
  max_wav_value: 32768.0
  top_db: 60
code:
  nclusters: 200
  hop_length: 320
  layer: 12
  model_path: ./ckpt/laughter_kmeans_200.model
  code_path: ./codes/laughter_200.txt
stft:
  n_fft: 1024
  window_length: 1024
  hop_length: 320
mel:
  n_mel: 80
  fmin: 0
  fmax: 8000
per_speaker_normalization: True
pitch:
  feature: "phoneme" # frame or phoneme
  normalization: True
  norm_method: "z_score"
energy:
  feature: "phoneme" # frame or phoneme
  normalization: True
  norm_method: "z_score"
